name: CI/CD Pipeline for Lootopia

on:
  push:
    branches:
      - 116-ci-frontend

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies (Expo web project)
        run: npm install
        working-directory: frontend

      - name: Build Expo web project
        run: npx expo export --platform web
        working-directory: frontend

      - name: Install Netlify CLI
        run: npm install -g netlify-cli
        working-directory: frontend
        
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --dir=dist --site=${{ secrets.SITE_ID }} --prod 
        working-directory: frontend